# Phase 1 — Data Download
**MAI603: Machine Learning | Ajman University**

This notebook downloads the US-Accidents dataset from Kaggle and performs the two-stage spatial-temporal merge to produce the 16.9M-row training corpus.

**Run all cells top to bottom (first time only).**

---

## Cell 1 — Kaggle API Setup
Install the Kaggle CLI and authenticate using your personal API token.

> ⚠️ **Replace `PASTE_YOUR_TOKEN_HERE` with your actual token.**  
> Get it from: [kaggle.com → Account → Create New Token](https://www.kaggle.com/settings)

In [6]:
import os
from dotenv import load_dotenv

# Load variables from .env file into environment
load_dotenv()

# Import and authenticate
import kaggle
kaggle.api.authenticate()

print("✅ Authenticated successfully using .env!")

# Verify authentication
datasets = kaggle.api.dataset_list(search="us-accidents")
print(f"Found {len(datasets)} datasets matching 'us-accidents'.")
!kaggle datasets list -s us-accidents

✅ Authenticated successfully using .env!
Found 20 datasets matching 'us-accidents'.
ref                                                             title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating  
--------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------  
sobhanmoosavi/us-accidents                                      US Accidents (2016 - 2023)                           684855912  2023-05-28 00:54:47.207000         189786       2697                1  
jonbown/us-2020-traffic-accidents                               US Traffic Accidents                                  82475267  2023-02-26 16:53:20.873000           4275         69                1  
sobhanmons/analysis-of-us-accidents                             Analysis of US accidents                            

In [7]:
import os
from dotenv import load_dotenv

# Load variables from .env file into environment
load_dotenv()

# Import and authenticate
import kaggle
kaggle.api.authenticate()

print("✅ Authenticated successfully using .env!")

# Verify authentication
datasets = kaggle.api.dataset_list(search="us-accidents")
print(f"Found {len(datasets)} datasets matching 'us-accidents'.")
!kaggle datasets list -s us-accidents

✅ Authenticated successfully using .env!
Found 20 datasets matching 'us-accidents'.
ref                                                             title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating  
--------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------  
sobhanmoosavi/us-accidents                                      US Accidents (2016 - 2023)                           684855912  2023-05-28 00:54:47.207000         189786       2697                1  
jonbown/us-2020-traffic-accidents                               US Traffic Accidents                                  82475267  2023-02-26 16:53:20.873000           4275         69                1  
sobhanmons/analysis-of-us-accidents                             Analysis of US accidents                            

In [8]:
import os
from dotenv import load_dotenv

# Load variables from .env file into environment
load_dotenv()

# Import and authenticate
import kaggle
kaggle.api.authenticate()

print("✅ Authenticated successfully using .env!")

# Verify authentication
datasets = kaggle.api.dataset_list(search="us-accidents")
print(f"Found {len(datasets)} datasets matching 'us-accidents'.")
!kaggle datasets list -s us-accidents

✅ Authenticated successfully using .env!
Found 20 datasets matching 'us-accidents'.
ref                                                             title                                                     size  lastUpdated                 downloadCount  voteCount  usabilityRating  
--------------------------------------------------------------  --------------------------------------------------  ----------  --------------------------  -------------  ---------  ---------------  
sobhanmoosavi/us-accidents                                      US Accidents (2016 - 2023)                           684855912  2023-05-28 00:54:47.207000         189786       2697                1  
jonbown/us-2020-traffic-accidents                               US Traffic Accidents                                  82475267  2023-02-26 16:53:20.873000           4275         69                1  
sobhanmons/analysis-of-us-accidents                             Analysis of US accidents                            

## Cell 2 — Load Project Directory

Set a local directory so all downloaded files are saved persistently to `./traffic_project`.

In [9]:
import os

# Set local project directory path (creates a 'traffic_project' folder inside your project workspace)
dest_folder = './traffic_project'
os.makedirs(dest_folder, exist_ok=True)

print(f"✅ Local project directory ready at: {os.path.abspath(dest_folder)}")

✅ Local project directory ready at: c:\Users\Mega-Pc\Desktop\malek\Traffic-Congestion-Prediction\traffic_project


## Cell 3 — Download US-Accidents Dataset
Download the full US-Accidents dataset (~3GB) directly into your Drive folder.

> ⏱️ **Runtime: 2–5 minutes** depending on connection speed.

In [10]:
import os

# Download the dataset directly into the local project folder (2-5 minutes)
!kaggle datasets download -d sobhanmoosavi/us-accidents -p "{dest_folder}" --unzip

# Check what got downloaded
!ls -lh "{dest_folder}"

Dataset URL: https://www.kaggle.com/datasets/sobhanmoosavi/us-accidents
License(s): CC-BY-NC-SA-4.0




  0%|          | 0.00/653M [00:00<?, ?B/s]
  0%|          | 1.00M/653M [00:00<06:16, 1.82MB/s]
  0%|          | 3.00M/653M [00:00<02:18, 4.92MB/s]
  1%|          | 5.00M/653M [00:00<01:33, 7.26MB/s]
  1%|          | 7.00M/653M [00:01<01:15, 9.00MB/s]
  1%|▏         | 9.00M/653M [00:01<01:05, 10.3MB/s]
  2%|▏         | 11.0M/653M [00:01<01:00, 11.2MB/s]
  2%|▏         | 13.0M/653M [00:01<00:56, 11.8MB/s]
  2%|▏         | 15.0M/653M [00:01<00:54, 12.3MB/s]
  3%|▎         | 17.0M/653M [00:01<00:52, 12.6MB/s]
  3%|▎         | 19.0M/653M [00:02<00:51, 12.8MB/s]
  3%|▎         | 21.0M/653M [00:02<00:51, 13.0MB/s]
  4%|▎         | 23.0M/653M [00:02<00:50, 13.1MB/s]
  4%|▍         | 25.0M/653M [00:02<00:50, 13.2MB/s]
  4%|▍         | 27.0M/653M [00:02<00:49, 13.2MB/s]
  4%|▍         | 29.0M/653M [00:02<00:49, 13.3MB/s]
  5%|▍         | 31.0M/653M [00:02<00:49, 13.3MB/s]
  5%|▌         | 33.0M/653M [00:03<00:48, 13.3MB/s]
  5%|▌         | 35.0M/653M [00:03<00:48, 13.3MB/s]
  6%|▌         | 37.

## Cell 4 — Filter to Bay Area 2017
From the 7.7M-row dataset, keep only:
- Records in the 9 SF Bay Area counties
- Records from calendar year 2017 (matches PEMS-BAY window)
- Only the 18 columns needed for this project

> ⏱️ **Runtime: 1–3 minutes** (chunked CSV read).

In [12]:
import pandas as pd
import glob
import os

# Define local folder path if not already defined
dest_folder = './traffic_project'

# Auto-find the CSV (name varies by Kaggle version)
csv_files = glob.glob(f"{dest_folder}/US_Accidents*.csv")
if not csv_files:
    raise FileNotFoundError(f"No US_Accidents CSV file found in {dest_folder}. Run the download step first.")

INPUT_PATH = csv_files[0]
OUTPUT_PATH = f"{dest_folder}/us_accidents_bay_2017.csv"
print(f"Input file found: {INPUT_PATH}")

KEEP_COLS = [
    'ID', 'Severity', 'Start_Time', 'End_Time',
    'Start_Lat', 'Start_Lng',
    'Distance(mi)', 'City', 'County', 'State',
    'Temperature(F)', 'Humidity(%)', 'Pressure(in)',
    'Visibility(mi)', 'Wind_Speed(mph)', 'Precipitation(in)',
    'Weather_Condition', 'Sunrise_Sunset'
]

BAY_COUNTIES = [
    'Santa Clara', 'Alameda', 'San Mateo',
    'San Francisco', 'Contra Costa',
    'Solano', 'Marin', 'Napa', 'Sonoma'
]

print("\nFiltering...")
chunks = []
total_rows = 0

for i, chunk in enumerate(pd.read_csv(
        INPUT_PATH, usecols=KEEP_COLS,
        chunksize=500_000, low_memory=False)):
    total_rows += len(chunk)
    chunk['Start_Time'] = pd.to_datetime(chunk['Start_Time'], errors='coerce')
    chunk = chunk[(chunk['Start_Time'] >= '2017-01-01') &
                  (chunk['Start_Time'] <  '2018-01-01')]
    chunk = chunk[(chunk['State'] == 'CA') & (chunk['County'].isin(BAY_COUNTIES))]
    if len(chunk) > 0:
        chunks.append(chunk)
    print(f"  Chunk {i+1}: scanned {total_rows:,}, kept {sum(len(c) for c in chunks):,}")

result = pd.concat(chunks, ignore_index=True)
result.to_csv(OUTPUT_PATH, index=False)

print(f"\n✅ Saved locally to: {OUTPUT_PATH}")
print(f"   Rows kept: {len(result):,}")
print(f"   Date range: {result['Start_Time'].min()} → {result['Start_Time'].max()}")
print(f"\n   Counties breakdown:")
print(result['County'].value_counts())

# File size check (Cross-platform Python alternative to `!ls -lh`)
file_size_mb = os.path.getsize(OUTPUT_PATH) / (1024 * 1024)
print(f"\n   File size: {file_size_mb:.2f} MB")

Input file found: ./traffic_project\US_Accidents_March23.csv

Filtering...
  Chunk 1: scanned 500,000, kept 15,956
  Chunk 2: scanned 1,000,000, kept 15,956
  Chunk 3: scanned 1,500,000, kept 15,956
  Chunk 4: scanned 2,000,000, kept 15,956
  Chunk 5: scanned 2,500,000, kept 15,956
  Chunk 6: scanned 3,000,000, kept 15,956
  Chunk 7: scanned 3,500,000, kept 26,781
  Chunk 8: scanned 4,000,000, kept 33,022
  Chunk 9: scanned 4,500,000, kept 33,022
  Chunk 10: scanned 5,000,000, kept 33,022
  Chunk 11: scanned 5,500,000, kept 33,022
  Chunk 12: scanned 6,000,000, kept 33,022
  Chunk 13: scanned 6,500,000, kept 33,022
  Chunk 14: scanned 7,000,000, kept 33,022
  Chunk 15: scanned 7,500,000, kept 33,022
  Chunk 16: scanned 7,728,394, kept 35,645

✅ Saved locally to: ./traffic_project/us_accidents_bay_2017.csv
   Rows kept: 35,645
   Date range: 2017-01-01 00:17:36 → 2017-12-31 22:55:06

   Counties breakdown:
County
Alameda          10448
Santa Clara       8183
Contra Costa      5156
San M

## Cell 6 — Verify Drive Files
Mount Drive and list the project folder to confirm all required PEMS-BAY files are present.

> ⚠️ Before continuing, ensure these files exist in `/traffic_project/`:
> - `pems-bay.h5` — speed data matrix
> - `pems-bay-meta.h5` — sensor GPS coordinates
> - `adj_mx_bay.pkl` — road network adjacency matrix
>
> Download PEMS-BAY from: https://zenodo.org/record/5724362

In [13]:
import os

# Set local project directory path
dest_folder = './traffic_project'

# List files present in your local folder
files = os.listdir(dest_folder)
print("Files found in local project folder:")
for f in files:
    print(f"  - {f}")

# Check for required PEMS-BAY files
required_files = ['adj_mx_bay.pkl', 'pems-bay.h5', 'pems-bay-meta.h5']
missing = [f for f in required_files if f not in files]

if missing:
    print(f"\n⚠️ Warning: The following required files are missing in {dest_folder}: {missing}")
else:
    print("\n✅ All required PEMS-BAY files are present!")

Files found in local project folder:
  - adj_mx_bay.pkl
  - deployment
  - pems-bay-meta.h5
  - pems-bay.h5
  - src
  - us_accidents_bay_2017.csv
  - US_Accidents_March23.csv

✅ All required PEMS-BAY files are present!


## Cell 7 — Install Additional Dependencies

In [14]:
%pip install -q pyarrow tables

Note: you may need to restart the kernel to use updated packages.


## Cell 8 — Load PEMS-BAY Speed Data & Sensor Metadata
Load the speed matrix (52,116 timesteps × 325 sensors) and extract sensor GPS coordinates from the metadata file.

In [16]:
import h5py
import numpy as np
import pandas as pd
import os

# Set local project folder
dest_folder = './traffic_project'

pems_h5 = os.path.join(dest_folder, 'pems-bay.h5')
meta_h5 = os.path.join(dest_folder, 'pems-bay-meta.h5')

# Check if required files exist
if not os.path.exists(pems_h5) or not os.path.exists(meta_h5):
    raise FileNotFoundError(
        f"Missing required HDF5 files in {dest_folder}.\n"
        f"Please ensure both 'pems-bay.h5' and 'pems-bay-meta.h5' are placed in {dest_folder}."
    )

# Load speed data
with h5py.File(pems_h5, 'r') as f:
    speeds = f['speed/block0_values'][:]       # (52116, 325)
    sensor_ids = f['speed/block0_items'][:]    # 325 sensor IDs
    time_ns = f['speed/axis1'][:]              # timestamps in nanoseconds

timestamps = pd.to_datetime(time_ns, unit='ns')
print(f"Speed matrix: {speeds.shape}")
print(f"Time range: {timestamps.min()} → {timestamps.max()}")
print(f"Sensors: {len(sensor_ids)}")

# Load sensor GPS coordinates from meta file
with h5py.File(meta_h5, 'r') as f:
    meta_cols = [c.decode() for c in f['meta/block0_items'][:]]
    meta_vals = f['meta/block0_values'][:]
    meta_sensor_ids = f['meta/axis1'][:]

meta_df = pd.DataFrame(meta_vals, columns=meta_cols)
meta_df['sensor_id'] = meta_sensor_ids
meta_df = meta_df[['sensor_id', 'Latitude', 'Longitude']]
print(f"\nSensor metadata:")
print(meta_df.head())

Speed matrix: (52116, 325)
Time range: 2017-01-01 00:00:00 → 2017-06-30 23:55:00
Sensors: 325

Sensor metadata:
   sensor_id   Latitude   Longitude
0     400649  37.251741 -121.958118
1     400715  37.256205 -121.955355
2     400240  37.258184 -121.953853
3     403329  37.270267 -121.947353
4     400436  37.271687 -121.947037


## Cell 9 — Reshape to Long Format
Convert the (52,116 × 325) speed matrix into a long-format DataFrame:
one row per (sensor, timestamp) = ~16.9M rows.
Attach GPS coordinates to each row.

In [17]:
# Convert (52116 × 325) matrix into a long format:
# one row per (sensor, timestamp) = 16.9M rows
print("Reshaping speed matrix into long format...")

# Build the long dataframe
long_df = pd.DataFrame(speeds, index=timestamps, columns=sensor_ids)
long_df.index.name = 'timestamp'
long_df.columns.name = 'sensor_id'
long_df = long_df.stack().reset_index()
long_df.columns = ['timestamp', 'sensor_id', 'speed']

print(f"Long format shape: {long_df.shape}")
print(long_df.head())

# Attach GPS coordinates
long_df = long_df.merge(meta_df, on='sensor_id', how='left')
print(f"\nWith GPS attached: {long_df.shape}")
print(f"Rows missing GPS: {long_df['Latitude'].isna().sum()}\n")
print(long_df.head())

Reshaping speed matrix into long format...
Long format shape: (16937700, 3)
   timestamp  sensor_id  speed
0 2017-01-01     400001   71.4
1 2017-01-01     400017   67.8
2 2017-01-01     400030   70.5
3 2017-01-01     400040   67.4
4 2017-01-01     400045   68.8

With GPS attached: (16937700, 5)
Rows missing GPS: 0

   timestamp  sensor_id  speed   Latitude   Longitude
0 2017-01-01     400001   71.4  37.364085 -121.901149
1 2017-01-01     400017   67.8  37.253303 -121.945440
2 2017-01-01     400030   70.5  37.359087 -121.906538
3 2017-01-01     400040   67.4  37.294949 -121.873109
4 2017-01-01     400045   68.8  37.363402 -121.902233


## Cell 10 — Load & Prepare Accident Data
Load the filtered Bay Area accident records and extract weather observations.
Each accident record carries certified weather readings from official meteorological stations.

In [18]:
# Set local project directory
dest_folder = './traffic_project'
acc_file = os.path.join(dest_folder, 'us_accidents_bay_2017.csv')

if not os.path.exists(acc_file):
    raise FileNotFoundError(f"Could not find {acc_file}. Please run Cell 4 first to generate the filtered CSV.")

# Load accident data
acc = pd.read_csv(acc_file)
acc['Start_Time'] = pd.to_datetime(acc['Start_Time'])

# Keep only accidents during PEMS-BAY's time window (Jan–Jun 2017)
# Plus a small buffer on either side for nearest-neighbor matching
acc = acc[(acc['Start_Time'] >= '2016-12-31') &
          (acc['Start_Time'] <= '2017-07-01')].copy()
print(f"Accidents in PEMS-BAY window: {len(acc):,}")

# Weather observations: one record per accident with its timestamp + weather
weather_obs = acc[['Start_Time', 'Start_Lat', 'Start_Lng',
                   'Temperature(F)', 'Humidity(%)', 'Visibility(mi)',
                   'Wind_Speed(mph)', 'Weather_Condition']].copy()
weather_obs = weather_obs.rename(columns={'Start_Time': 'obs_time'})
weather_obs = weather_obs.sort_values('obs_time').reset_index(drop=True)
print(f"Weather observations: {len(weather_obs):,}")

Accidents in PEMS-BAY window: 19,733
Weather observations: 19,733


## Cell 11 — Stage 1: Weather Enrichment
For each sensor reading (s, t), find the closest accident record in time within ±4 hours and ±50km.
Transfer its weather observations (temperature, humidity, visibility, wind speed, weather condition).

> ⏱️ **Runtime: 5–10 minutes**  
> Achieves **97.8% weather coverage** across all sensor readings.

In [19]:
# For each sensor, do merge_asof against weather observations
# We do this per-sensor because merge_asof is a time-based match
print("Merging weather for each sensor (this takes ~5-10 min)...")

from tqdm import tqdm

long_df['timestamp'] = long_df['timestamp'].astype('datetime64[ns]')
weather_obs['obs_time'] = weather_obs['obs_time'].astype('datetime64[ns]')

results = []
unique_sensors = long_df['sensor_id'].unique()

for sid in tqdm(unique_sensors, desc='Weather merge'):
    sensor_rows = long_df[long_df['sensor_id'] == sid].sort_values('timestamp').copy()

    merged = pd.merge_asof(
        sensor_rows,
        weather_obs[['obs_time', 'Temperature(F)', 'Humidity(%)',
                     'Visibility(mi)', 'Wind_Speed(mph)', 'Weather_Condition']],
        left_on='timestamp', right_on='obs_time',
        direction='nearest',
        tolerance=pd.Timedelta('4h')
    )
    merged = merged.drop(columns=['obs_time'])
    results.append(merged)

merged_df = pd.concat(results, ignore_index=True)
print(f"\nAfter weather merge: {merged_df.shape}")
print(f"Weather coverage: {merged_df['Temperature(F)'].notna().mean()*100:.1f}%")

Merging weather for each sensor (this takes ~5-10 min)...


Weather merge: 100%|██████████| 325/325 [00:05<00:00, 56.42it/s]



After weather merge: (16937700, 10)
Weather coverage: 97.8%


## Cell 12 — Stage 2: Accident Context Features
For each (sensor, timestamp), count accidents within 5km in the past 60 minutes.
Derives three features:
- `acc_count_60min` — number of nearby accidents in the lookback window
- `acc_max_severity` — maximum severity (1–4) of those accidents
- `acc_mins_since` — minutes since the most recent nearby accident

> ⏱️ **Runtime: 5–15 minutes**  
> Window computed on strictly past data — no look-ahead bias.

In [20]:
print("Computing accident context features (this takes ~5-15 min)...")

from math import radians

NEARBY_KM = 5.0
WINDOW_MIN = 60

# Pre-compute radians for all accidents (once)
acc_lat_rad = np.radians(acc['Start_Lat'].values)
acc_lon_rad = np.radians(acc['Start_Lng'].values)
acc_times = acc['Start_Time'].values
acc_sev = acc['Severity'].values

# For each sensor, find accidents within 5 km (spatial filter, done once per sensor)
# Then for each timestep, find which of those happened in past 60 min

def compute_accident_features_for_sensor(sid):
    s_meta = meta_df[meta_df['sensor_id'] == sid].iloc[0]
    s_lat, s_lon = np.radians(s_meta['Latitude']), np.radians(s_meta['Longitude'])

    # Haversine distance to all accidents
    dlat = acc_lat_rad - s_lat
    dlon = acc_lon_rad - s_lon
    a = np.sin(dlat/2)**2 + np.cos(s_lat)*np.cos(acc_lat_rad)*np.sin(dlon/2)**2
    dist = 2 * 6371 * np.arcsin(np.sqrt(a))

    # Keep only nearby accidents (spatial filter)
    nearby_mask = dist <= NEARBY_KM
    nearby_times = acc_times[nearby_mask]
    nearby_sev = acc_sev[nearby_mask]

    # For each timestep of this sensor, count accidents in past 60 min
    sensor_rows = merged_df[merged_df['sensor_id'] == sid]
    timesteps = sensor_rows['timestamp'].values

    counts = np.zeros(len(timesteps), dtype=np.int32)
    max_sevs = np.zeros(len(timesteps), dtype=np.int32)
    mins_since = np.full(len(timesteps), WINDOW_MIN, dtype=np.float32)

    window_ns = np.timedelta64(WINDOW_MIN, 'm')

    for i, ts in enumerate(timesteps):
        window_start = ts - window_ns
        in_window = (nearby_times >= window_start) & (nearby_times <= ts)
        n = in_window.sum()
        counts[i] = n
        if n > 0:
            max_sevs[i] = nearby_sev[in_window].max()
            most_recent = nearby_times[in_window].max()
            mins_since[i] = (ts - most_recent) / np.timedelta64(1, 'm')

    return sensor_rows.index, counts, max_sevs, mins_since

# Initialize columns
merged_df['acc_count_60min'] = 0
merged_df['acc_max_severity'] = 0
merged_df['acc_mins_since'] = float(WINDOW_MIN)

for sid in tqdm(unique_sensors, desc='Accident features'):
    idx, counts, sevs, mins = compute_accident_features_for_sensor(sid)
    merged_df.loc[idx, 'acc_count_60min'] = counts
    merged_df.loc[idx, 'acc_max_severity'] = sevs
    merged_df.loc[idx, 'acc_mins_since'] = mins

print(f"\n✅ Accident features computed")
print(f"   Rows with nearby accident in past hour: {(merged_df['acc_count_60min'] > 0).sum():,}")
print(f"   Rows with no nearby accident:           {(merged_df['acc_count_60min'] == 0).sum():,}")

Computing accident context features (this takes ~5-15 min)...


Accident features: 100%|██████████| 325/325 [02:51<00:00,  1.89it/s]


✅ Accident features computed
   Rows with nearby accident in past hour: 1,923,310
   Rows with no nearby accident:           15,014,390


## Cell 13 — Add Time Features & Save
Derive temporal features (hour, day of week, weekend indicator).
Reorder columns into the final 16-feature schema and save as a compressed Parquet file.

In [21]:
# Time-based features
merged_df['hour'] = merged_df['timestamp'].dt.hour
merged_df['dayofweek'] = merged_df['timestamp'].dt.dayofweek
merged_df['is_weekend'] = (merged_df['dayofweek'] >= 5).astype(int)

# Reorder columns into final 16-feature schema
col_order = [
    'timestamp', 'sensor_id', 'Latitude', 'Longitude', 'speed',
    'hour', 'dayofweek', 'is_weekend',
    'Temperature(F)', 'Humidity(%)', 'Visibility(mi)',
    'Wind_Speed(mph)', 'Weather_Condition',
    'acc_count_60min', 'acc_max_severity', 'acc_mins_since'
]
merged_df = merged_df[col_order]

# Save as parquet locally (compact, fast to reload)
output_path = os.path.join(dest_folder, 'merged_dataset_full.parquet')
merged_df.to_parquet(output_path, index=False, compression='snappy')

print(f"✅ Saved locally to: {output_path}")
print(f"   Rows: {len(merged_df):,}")
print(f"   Columns: {len(merged_df.columns)}")

# Show file size (Cross-platform Python alternative to `!ls -lh`)
file_size_mb = os.path.getsize(output_path) / (1024 * 1024)
print(f"   File size: {file_size_mb:.2f} MB")

✅ Saved locally to: ./traffic_project\merged_dataset_full.parquet
   Rows: 16,937,700
   Columns: 16
   File size: 97.83 MB


## Cell 14 — Final Dataset Summary
Print shape, memory usage, feature coverage, and Pearson correlations with speed to verify the merged dataset is correct.

In [22]:
print("="*60)
print("FINAL DATASET SUMMARY")
print("="*60)
print(f"Shape: {merged_df.shape}")
print(f"Memory: {merged_df.memory_usage(deep=True).sum() / 1024**2:.1f} MB")
print(f"Time range: {merged_df['timestamp'].min()} → {merged_df['timestamp'].max()}")
print(f"Unique sensors: {merged_df['sensor_id'].nunique()}")

print(f"\nSpeed stats:")
print(merged_df['speed'].describe().round(2))

print(f"\nFeature coverage (% non-null):")
for col in merged_df.columns:
    pct = merged_df[col].notna().mean() * 100
    print(f"  {col:25s}  {pct:6.2f}%")

print(f"\nCorrelations with speed:")
numeric_cols = ['Temperature(F)', 'Humidity(%)', 'Visibility(mi)',
                'Wind_Speed(mph)', 'acc_count_60min', 'acc_max_severity',
                'hour', 'is_weekend']
for col in numeric_cols:
    corr = merged_df[['speed', col]].corr().iloc[0, 1]
    print(f"  {col:25s}  r = {corr:+.3f}")

FINAL DATASET SUMMARY
Shape: (16937700, 16)
Memory: 2014.8 MB
Time range: 2017-01-01 00:00:00 → 2017-06-30 23:55:00
Unique sensors: 325

Speed stats:
count    16937700.00
mean           62.62
std             9.59
min             0.00
25%            62.10
50%            65.30
75%            67.50
max            85.10
Name: speed, dtype: float64

Feature coverage (% non-null):
  timestamp                  100.00%
  sensor_id                  100.00%
  Latitude                   100.00%
  Longitude                  100.00%
  speed                      100.00%
  hour                       100.00%
  dayofweek                  100.00%
  is_weekend                 100.00%
  Temperature(F)              97.81%
  Humidity(%)                 97.77%
  Visibility(mi)              97.78%
  Wind_Speed(mph)             81.33%
  Weather_Condition           97.77%
  acc_count_60min            100.00%
  acc_max_severity           100.00%
  acc_mins_since             100.00%

Correlations with speed:
  Te